# Generated by Django 4.1.3 on 2023-01-17 19:55

from django.db import migrations, models
import django.db.models.deletion
import photographer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('bio', models.CharField(max_length=200)),
                ('profile', models.ImageField(upload_to=photographer.models.profile_upload)),
                ('brand_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('other_addy', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=photographer.models.media_upload)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to='photographer.photographer')),
            ],
        ),
    ]
