# Generated by Django 4.1.3 on 2023-01-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='password',
            field=models.CharField(default='demo', max_length=150),
            preserve_default=False,
        ),
    ]
