# Generated by Django 4.1.5 on 2023-01-28 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0002_photographer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='alt',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photographer',
            name='max_price',
            field=models.DecimalField(decimal_places=10, default=10.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photographer',
            name='min_price',
            field=models.DecimalField(decimal_places=10, default=10.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photographer',
            name='phone_num',
            field=models.CharField(default='08023287514', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photographer',
            name='brand_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
