# Generated by Django 4.1.5 on 2023-02-01 19:20

from django.db import migrations, models
import django.db.models.deletion
import snapshotapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('bio', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_num', models.CharField(max_length=20, unique=True)),
                ('profile', models.ImageField(upload_to=snapshotapp.models.profile_upload)),
                ('brand_name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('other_addy', models.CharField(max_length=150)),
                ('min_price', models.DecimalField(decimal_places=10, max_digits=15)),
                ('max_price', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=snapshotapp.models.media_upload)),
                ('alt', models.CharField(blank=True, max_length=60, null=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to='snapshotapp.photographer')),
            ],
        ),
    ]
